
-- Ajuste --

ALTER TABLE `CB04_EMPRESA` ADD FOREIGN KEY (`CB04_CATEGORIA_ID`) REFERENCES `cashback`.`CB10_CATEGORIA`(`CB10_ID`) ON DELETE RESTRICT ON UPDATE NO ACTION;
ALTER TABLE `CB07_CASH_BACK` ADD PRIMARY KEY(`CB07_ID`);
ALTER TABLE `CB07_CASH_BACK` CHANGE `CB07_ID` `CB07_ID` INT(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE `CB07_CASH_BACK` CHANGE `CB07_PERCENTUAL` `CB07_PERCENTUAL` DECIMAL(10,2) NOT NULL;
ALTER TABLE `CB00_TRANSFERENCIA` ADD `CB00_COD_BANCO` INT NOT NULL AFTER `CB00_DT_CONCLUSAO`, ADD `CB00_TP_CONTA` INT NOT NULL AFTER `CB00_COD_BANCO`, ADD `CB00_NUM_CONTA` INT NOT NULL AFTER `CB00_TP_CONTA`, ADD `CB00_AGENCIA` VARCHAR(5) NOT NULL AFTER `CB00_NUM_CONTA`;
ALTER TABLE `CB00_TRANSFERENCIA` CHANGE `CB00_ID` `CB00_ID` INT(11) NOT NULL AUTO_INCREMENT;

-- VIEW
CREATE
ALGORITHM = UNDEFINED
SQL SECURITY INVOKER
VIEW `VIEW_EXTRATO_CLIENTE`
AS SELECT CB01_TRANSACAO.CB01_ID AS TRANSACAO_ID,
'NULL' AS TRANSFERENCIA_ID,
'TRANSAÇÃO' AS TIPO,
CB04_EMPRESA.CB04_ID AS EMPRESA_ID,
CB04_EMPRESA.CB04_NOME AS EMPRESA_NM, 
CB01_TRANSACAO.CB01_DT_COMPRA AS DT1,		
'NULL' AS DT2,
CB01_TRANSACAO.CB01_VALOR_COMPRA AS VLR1, 	
CB01_TRANSACAO.CB01_VALOR_DEVOLTA AS VLR2, 	
CB01_TRANSACAO.CB01_STATUS AS STATUS,
CB01_TRANSACAO.CB01_CLIENTE_ID AS CLIENTE
FROM CB01_TRANSACAO
INNER JOIN CB04_EMPRESA ON(CB04_EMPRESA.CB04_ID=CB01_TRANSACAO.CB01_EMPRESA_ID)

UNION

SELECT 'NULL' AS TRANSACAO_ID,
CB00_TRANSFERENCIA.CB00_ID AS TRANSFERENCIA_ID,
'TRANSFERÊNCIA' AS TIPO,
'NULL' AS EMPRESA_ID,
'NULL' AS EMPRESA_NM, 
CB00_TRANSFERENCIA.CB00_DT_SOLICITACAO AS DT1,
CB00_TRANSFERENCIA.CB00_DT_CONCLUSAO AS DT2,
CB00_TRANSFERENCIA.CB00_VALOR_TRANSFERIDO AS VLR1,	
(CB00_TRANSFERENCIA.CB00_VALOR_TRANSFERIDO * (-1)) AS VLR2,
CB00_TRANSFERENCIA.CB00_STATUS AS STATUS,
CB00_TRANSFERENCIA.CB00_CLIENTE_ID AS CLIENTE
FROM CB00_TRANSFERENCIA

ORDER BY DT1 DESC





    

---------------------	DADOS PARA TESTE ----------------------
-- add usuario
INSERT INTO `CB02_CLIENTE` (`CB02_ID`, `CB02_NOME`, `CB02_CPF`, `CB02_EMAIL`, `CB02_STATUS`, `CB02_DT_CADASTRO`) VALUES (NULL, 'Eduardo Matias', '535.334.688-28', 'emailteste@test.com', '1', CURRENT_TIMESTAMP);

-- add categorias
INSERT INTO `CB10_CATEGORIA` (`CB10_ID`, `CB10_NOME`, `CB10_STATUS`) VALUES (NULL, 'Motel', '1'), (NULL, 'Hotel', '1');

-- add empresa
INSERT INTO `CB04_EMPRESA` (`CB04_ID`, `CB04_NOME`, `CB04_CATEGORIA_ID`, `CB04_FUNCIONAMENTO`, `CB04_OBSERVACAO`, `CB04_STATUS`, `CB04_QTD_FAVORITO`, `CB04_QTD_COMPARTILHADO`, `CB04_END_LOGRADOURO`, `CB04_END_BAIRRO`, `CB04_END_CIDADE`, `CB04_END_UF`, `CB04_END_NUMERO`, `CB04_END_COMPLEMENTO`, `CB04_END_CEP`) VALUES (NULL, 'Empresa teste', '1', 'Sobre o funcionamento da empresa...', 'Observações...', '1', '4', '3', 'Av. avenida teste', 'Centro', 'Contagem', 'MG', 'S/N', 'Ao lado do posto de gasolina', '32010200');

-- add transacoes
INSERT INTO `CB01_TRANSACAO` (`CB01_ID`, `CB01_CLIENTE_ID`, `CB01_EMPRESA_ID`, `CB01_DT_COMPRA`, `CB01_STATUS`, `CB01_VALOR_COMPRA`, `CB01_VALOR_DEVOLTA`) VALUES (NULL, '1', '1', CURRENT_TIMESTAMP, '1', '100.00', '20.00'), (NULL, '1', '1', '2017-03-15 12:47:10', '1', '350', '70.00');

-- add produto
INSERT INTO `CB05_PRODUTO` (`CB05_ID`, `CB05_EMPRESA_ID`, `CB05_TITULO`, `CB05_DESCRICAO`) VALUES (NULL, '1', 'Produto de teste', 'Exemplo de descrição para o produto de teste da empresa de teste');

-- add forma de pagamento
INSERT INTO `CB08_FORMA_PAGAMENTO` (`CB08_ID`, `CB08_NOME`, `CB08_URL_IMG`, `CB08_STATUS`) VALUES (NULL, 'Meu Checkout', '', '1'), (NULL, 'Visa', '', '1');

-- add forma de pagamento para a empresa
INSERT INTO `CB09_FORMA_PAG_EMPRESA` (`CB09_EMPRESA_ID`, `CB09_FORMA_PAG_ID`) VALUES ('1', '1'), ('1', '2');

-- add item da categoria 
INSERT INTO `CB11_ITEM_CATEGORIA` (`CB11_ID`, `CB11_CATEGORIA_ID`, `CB11_DESCRICAO`, `CB11_STATUS`) VALUES (NULL, '1', 'Item 1 da cat 1', '1'), (NULL, '1', 'Item 2 da cat 1', '1');

-- add vinculo do item da categoria no produto
INSERT INTO `CB12_ITEM_CATEG_EMPRESA` (`CB12_ID`, `CB12_ITEM_ID`, `CB12_EMPRESA_ID`, `CB12_PRODUTO_ID`) VALUES (NULL, '1', NULL, '1'), (NULL, '2', NULL, '1');

-- add transferencia
INSERT INTO `CB00_TRANSFERENCIA` (`CB00_ID`, `CB00_CLIENTE_ID`, `CB00_DT_SOLICITACAO`, `CB00_DT_CONCLUSAO`, `CB00_COD_BANCO`, `CB00_TP_CONTA`, `CB00_NUM_CONTA`, `CB00_AGENCIA`, `CB00_STATUS`, `CB00_VALOR_TRANSFERIDO`) VALUES ('', '1', '2017-03-18 12:25:36', NULL, '123', '4', '12344323', '532', '2', '100');

-----------------------------------------------------------------




